cat_dict = {
    "category_0000AENKO6xFbB3W4JxRTt": "withdrawals",
    "category_0000AEOBtI7HRcgIejCxLH": "refunds",
    "category_0000AEMSmYtFzXR0uPKWGn": "healthcare",
    "category_0000AENK9Mgep9HzznTMxN": "pets",
    "category_0000AENKyHSe0v91qvv2zi": "home",
    "category_0000AENKIsNwLAM0r8kdjF": "fees",
    "category_0000AENKfrIYY0HwCYh4dt": "crypto",
    "category_0000AEMzpjxiZzwnPD4HrN": "subscriptions",
    "category_0000AExUhOiHn4sDap8sYz": "gym",
    "category_0000AEO9FSicPHpdGVswdd": "clothes",
    "category_0000AENKq0a0tSTkK0RFPF": "haircut",
    "category_0000AF0vvfmQPiKmgwAzGT": "education",
    "category_0000AF0wMb8Rn7V96E5mIk": "stocks",
    "category_0000AF0vVufoPz8RLxnejp": "isa",
}

columns_dict = {
    "id_x": "id",
    "id_y": "merchant_id",
    "name": "merchant_description",
    "category_x": "category",
    "category_y": "merchant_category",
    "category_0000AENKO6xFbB3W4JxRTt": "monzo_category_withdrawals",
    "category_0000AEOBtI7HRcgIejCxLH": "monzo_category_refunds",
    "category_0000AEMSmYtFzXR0uPKWGn": "monzo_category_healthcare",
    "category_0000AENK9Mgep9HzznTMxN": "monzo_category_pets",
    "category_0000AENKyHSe0v91qvv2zi": "monzo_category_home",
    "category_0000AENKIsNwLAM0r8kdjF": "monzo_category_fees",
    "category_0000AENKfrIYY0HwCYh4dt": "monzo_category_crypto",
    "category_0000AEMzpjxiZzwnPD4HrN": "monzo_category_subscriptions",
    "category_0000AExUhOiHn4sDap8sYz": "monzo_category_gym",
    "category_0000AEO9FSicPHpdGVswdd": "monzo_category_clothes",
    "category_0000AENKq0a0tSTkK0RFPF": "monzo_category_haircut",
    "category_0000AF0vvfmQPiKmgwAzGT": "monzo_category_education",
    "category_0000AF0vVufoPz8RLxnejp": "monzo_category_isa",
    "category_0000AF0wMb8Rn7V96E5mIk": "monzo_category_stocks",
    "income": "monzo_category_income",
    "transfers": "monzo_category_transfers",
    "bills": "monzo_category_bills",
    "eating_out": "monzo_category_eating_out",
    "general": "monzo_category_general",
    "expenses": "monzo_category_expenses",
    "gifts": "monzo_category_gifts",
    "shopping": "monzo_category_shopping",
    "entertainment": "monzo_category_entertainment",
    "groceries": "monzo_category_groceries",
    "holidays": "monzo_category_holidays",
    "transport": "monzo_category_transport",
    "savings": "monzo_category_savings",
}

monzo_categories_lst = [
    "monzo_category_withdrawals",
    "monzo_category_refunds",
    "monzo_category_healthcare",
    "monzo_category_pets",
    "monzo_category_home",
    "monzo_category_fees",
    "monzo_category_crypto",
    "monzo_category_subscriptions",
    "monzo_category_gym",
    "monzo_category_clothes",
    "monzo_category_haircut",
    "monzo_category_education",
    "monzo_category_isa",
    "monzo_category_stocks",
    "monzo_category_income",
    "monzo_category_transfers",
    "monzo_category_bills",
    "monzo_category_eating_out",
    "monzo_category_general",
    "monzo_category_expenses",
    "monzo_category_gifts",
    "monzo_category_shopping",
    "monzo_category_entertainment",
    "monzo_category_groceries",
    "monzo_category_holidays",
    "monzo_category_transport",
    "monzo_category_savings",
]

compare_transaction_cols = [
    "id",
    "date",
    "description",
    "amount",
    "category",
    "merchant_description",
    "logo",
    "emoji",
    "merchant_category",
    "notes",
    "monzo_category_transport",
    "monzo_category_transfers",
    "monzo_category_groceries",
    "monzo_category_crypto",
    "monzo_category_subscriptions",
    "monzo_category_eating_out",
    "monzo_category_shopping",
    "monzo_category_healthcare",
    "monzo_category_pets",
    "monzo_category_gifts",
    "monzo_category_entertainment",
    "monzo_category_bills",
    "monzo_category_home",
    "monzo_category_gym",
    "monzo_category_income",
    "monzo_category_clothes",
    "monzo_category_haircut",
    "monzo_category_refunds",
    "monzo_category_education",
    "monzo_category_fees",
    "monzo_category_stocks",
    "monzo_category_isa",
    "monzo_category_withdrawals",
    "monzo_category_savings",
    "monzo_category_holidays",
]
